import { writeFile } from 'node:fs/promises';
import { CURRICULUM } from '../js/lessons.js';
import { KEYBOARD_PRESETS, KeyboardView, keyboardLayout } from '../js/keyboard.js';

// Build-time content and geometry only. The Swift app owns runtime behavior.
const layouts = Object.fromEntries(Object.entries(KEYBOARD_PRESETS).map(([preset, label]) => {
    const layout = keyboardLayout(preset);
    const home = Array.from(layout.homeKeys.toUpperCase());
    const restHint = `Rest your fingers on ${home.slice(0, 4).join(' ')} and ` +
        home.slice(4).join(' ');
    const handsContainer = { innerHTML: '' };
    KeyboardView.prototype.renderHands.call({ layout, restHint, handsContainer });
    return [preset, { ...layout, label, handsHTML: handsContainer.innerHTML }];
}));
const collation = Array.from({ length: 95 }, (_, index) => String.fromCharCode(index + 32))
    .sort((a, b) => a.localeCompare(b, 'en')).join('');
const data = JSON.stringify({ curriculum: CURRICULUM, layouts, collation });
if (data.includes('"""#')) throw new Error('Catalog contains a Swift raw-string delimiter.');
await writeFile(new URL('../swift/Sources/Catalog.generated.swift', import.meta.url),
    '// Generated by scripts/swift-catalog.mjs from the existing content and geometry.\n' +
    '// Runtime decisions are implemented in Practice.swift and Guides.swift.\n' +
    'enum SwiftCatalog {\n    static let data: JSON = JSON.parse(#"""\n' + data +
    '\n"""#)!\n}\n');
console.log('Generated static Swift lesson, word, quote and keyboard catalog.');
